### ISSUE TITLE
Utils - add some examples

### ISSUE THREAD

**Issue by JayAshton** [hmcts/tcoe-playwright-example#6]
Things like logging in via IDAM will be common across test packs, it makes sense to provide an example util/helper class of each for doing so

### Tasks
- [ ] log in helper (via API)
- [ ] create case helper (via API)
- [ ] create citizen user per test (via API)
- [ ] User ingestion (via API)
